### ISSUE TITLE
m3u8 upload fail handling

### ISSUE THREAD

**Issue by DaWe35** [DaWe35/SkyLive#28]
Related to https://github.com/DaWe35/SkyLive/issues/15
We need to make m3u8 uploading fault tolerant

**Comment by DaWe35** [comment]
```
Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fc1433ba198>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc1433ba198>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stream_hls.py", line 265, in <module>
    curses.wrapper(worker)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "stream_hls.py", line 227, in worker
    share(nextToShare, filearr)
  File "stream_hls.py", line 151, in share
    x = requests.post(config.m3u8_list_upload_path, data = post)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc1433ba198>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```

**Comment by DaWe35** [comment]
``` python

Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5261351a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5261351a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stream_hls.py", line 265, in <module>
    curses.wrapper(worker)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "stream_hls.py", line 227, in worker
    share(nextToShare, filearr)
  File "stream_hls.py", line 151, in share
    x = requests.post(config.m3u8_list_upload_path, data = post)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5261351a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))


```

**Comment by DaWe35** [comment]
``` python




  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ether/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbba46a12e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stream_hls.py", line 265, in <module>
    curses.wrapper(worker)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "stream_hls.py", line 227, in worker
    share(nextToShare, filearr)
  File "stream_hls.py", line 151, in share
    x = requests.post(config.m3u8_list_upload_path, data = post)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='skylive.coolhd.hu', port=443): Max retries exceeded with url: /write.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbba46a12e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```
